### ISSUE TITLE
Avatar and details page show the JSON 

### ISSUE THREAD

**Issue by beshoo** [outl1ne/nova-translatable#101]
Nova : v4.26.1 (Silver Surfer) 

![image](https://github.com/outl1ne/nova-translatable/assets/4635115/3e7d670b-71cf-4015-947c-c4e340da10bd)

```
  "php": "^8.1",
        "laravel/framework": "^10.8",
        "laravel/nova": "~4.0",
        "outl1ne/nova-translatable": "^2.1",
        "spatie/laravel-translatable": "^6.5",
        "tymon/jwt-auth": "^2.0"
```

https://github.com/outl1ne/nova-translatable/issues/78

**Comment by beshoo** [comment]
withBreadcrumbs 
![image](https://github.com/outl1ne/nova-translatable/assets/4635115/e1f548b2-0a9d-4038-96f3-d3f67d442286)

**Comment by Tarpsvo** [comment]
Heya! I suggest you use the HasTranslations trait and spatie/laravel-translatable. Referenced in step 1 of the installation:
https://github.com/outl1ne/nova-translatable#installation

**Comment by beshoo** [comment]
I already used it ... check this out 
the problem in the user menu!
![image](https://github.com/outl1ne/nova-translatable/assets/4635115/899978a3-4fdf-4657-bc63-df61e6a9e7f5)
![image](https://github.com/outl1ne/nova-translatable/assets/4635115/cb183da9-2335-48ed-a664-ba0f7013a2f8)

**Comment by Tarpsvo** [comment]
Seems like an issue with how Nova queries the User resource.

You can use this to fix it in the header:
Models/User.php:

```
public function toArray()
    {
        return array_merge(parent::toArray(), ['name' => $this->name]);
    }
```

**Comment by beshoo** [comment]
> Collaborator

Thats fix the problem , but.. shuled we report this to Nova!?
