### ISSUE TITLE
Add tinymce field

### ISSUE THREAD

**Issue by mialyGit** [outl1ne/nova-translatable#102]
how this package work with tinymce :https://github.com/emilianotisato/nova-tinymce

**Comment by Tarpsvo** [comment]
Don't know

**Comment by mialyGit** [comment]
@Tarpsvo This gives like this when I add Tinymce , 

![not](https://github.com/outl1ne/nova-translatable/assets/50203282/e9e5dbcd-95c8-4c7d-8675-3c11964c1f40)

**Comment by mialyGit** [comment]
This is my code : 

public function fields(NovaRequest $request)
    {
        return [
            TinymceEditor::make(__('Content'), 'content')
            ->translatable()
        ];
    }

**Comment by wajdijurry** [comment]
> @Tarpsvo This gives like this when I add Tinymce ,
> 
> ![not](https://user-images.githubusercontent.com/50203282/250229713-e9e5dbcd-95c8-4c7d-8675-3c11964c1f40.PNG)

I have the same issue.

@Tarpsvo How come this is closed?! This package corrupted the Tinymce field as illustrated by @mialyGit.

We wish this to be fixed ASAP.
