### ISSUE TITLE
rulesFor is not working

### ISSUE THREAD

**Issue by marcelosantos89** [outl1ne/nova-translatable#104]
Hey, i'm trying to validate some fields using rulesFor() but nothing is taking effect.

```       
           Text::make('Slug')
                ->hideFromIndex()
                ->translatable()
                ->rules(['max:255']) // Works
                ->rulesFor('en', [  // **Does not work**
                    'required'
                ])
                ->rulesFor(['pt', 'es', 'en'], function ($locale) { // **Does not work**
                    return ["unique:opportunities,slug->$locale{{resourceId}}"];
                }),
``` 

I tried to figure out the problem but I can't really get what's wrong.
I'm using:
- Laravel 9.52.14
- Nova 4.22.2

**Comment by BobbyBorisov** [comment]
@marcelosantos89 I think you are missing the trait `HandlesTranslatable`. [Link](https://github.com/outl1ne/nova-translatable#validation) to the documentation

**Comment by marcelosantos89** [comment]
@BobbyBorisov you are right I totally forgot that, Thank you.
