### ISSUE TITLE
Unnecessary border-t when field is first in Panel

### ISSUE THREAD

**Issue by mrleblanc101** [outl1ne/nova-translatable#119]
<img width="1502" alt="Screenshot 2024-03-17 at 4 15 34 PM" src="https://github.com/outl1ne/nova-translatable/assets/17392251/4d3da4de-b8fc-4c1c-afb6-328f14c6f485">

**Comment by mrleblanc101** [comment]
Nova has already `divide-y divide-gray-100` on the parent, so I don't even think the `boder-t` class is necessary at all

**Comment by Tarpsvo** [comment]
Thanks! Fixed in 2.3.0.
