### ISSUE TITLE
Validation error message localization

### ISSUE THREAD

**Issue by mehak-softuvo** [outl1ne/nova-translatable#63]
Hi,

**Question : Error messages coming like**  - The name.ar field is required.
I want to display Like The name field is required.

How to do that?

I have tried by adding in editor and validation.php file

**Comment by mehak-softuvo** [comment]
Hi Guys

Any update

**Comment by Kenny201** [comment]
I subscribe, the same problem!

**Comment by Tarpsvo** [comment]
Hi! 

You would have to specify the attribute names in `validation.php`. See docs here: https://laravel.com/docs/8.x/validation#specifying-attribute-in-language-files

Like this:
```php
'attributes' => [
  'name.ar' => 'Name',
],
```

I remember experimenting with this to get the validation error messages to work better, but for some reason, I didn't manage to make it work. There might be a better way though, it would be really helpful is someone investigated further into this. :)
