### ISSUE TITLE
Illuminate\\Database\\Grammar::parameterize(): Argument #1 ($values) must be of type array, int given

### ISSUE THREAD

**Issue by uzdeveloper1** [outl1ne/nova-translatable#77]
### **My fields**

Text::make(__('service.title'), 'title')
                ->translatable()
                ->rules(['max:255'])
                ->rulesFor('en', [
                    'required',
                ]),
Text::make(__('service.title'), 'description')
                ->translatable()
                ->rulesFor('en', [
                    'required',
                ]),

### **MyConfig**

return [

    /**
     * The locales which the `translatable` wrapper will use by default.
     *
     * Can be a:
     *  - Keyed array (['en' => 'English])
     *  - Callable that returns a keyed array
     */
    'locales' => [
        'ru' => 'Russian',
        'en' => 'English'
    ],

    /**
     * If enabled, the Nova's current locale will always be displayed as
     * the first locale in the tabs arrangement.
     *
     * If disabled, the locales array order is respected.
     */
    'prioritize_nova_locale' => true,

    /**
     * Defines the display type for the translatable tabs.
     *
     * Available options are: 'row', 'column', 'none'
     */
    'display_type' => 'row',

    /**
     * Defines the display type for the translatable select.
     *
     * Available options are: 'left-absolute', 'left-static', 'right-absolute', 'right-static
     */
    'locale_select.display_type' => 'right-absolute',

    /**
     * If set to a locale key, the translatable fields will automatically fill other
     * locales of the field's value when saving the field from the defined "default"
     * locale.
     *
     * Set to locale key (`en`, `ru`, etc) or null to enable/disable.
     */
    'fill_other_locales_from' => 'ru',

];

**Comment by uzdeveloper1** [comment]
I found

**Comment by bendadaniel** [comment]
Hi @uzdeveloper1 , how do you fix this problem? I have same problem, I can fix it by cast model's column to json. Is there any another fix?

**Comment by GxSupport** [comment]
Hi @bendadaniel forgot to add HasTranslations and $translatable to the model

`class Country extends Model
{
    use HasTranslations;
    protected $table="countries";
    public $translatable = ['title'];
}
`
