### ISSUE TITLE
Broken translated texta values on index/details views with Nova 4.12.x update

### ISSUE THREAD

**Issue by miks** [outl1ne/nova-translatable#78]
After updating Nova to 4.12.x text on index/details views are now displayed as raw JSON or "[object Object]".
I'm unsure whether this is a "nova-translatable" or Nova issue.

Index view:
<img width="302" alt="Screenshot 2022-07-14 at 11 37 40" src="https://user-images.githubusercontent.com/686243/178941023-0c6480b4-b092-46b5-9920-3c98f2d71703.png">

Details view:
<img width="695" alt="Screenshot 2022-07-14 at 11 37 54" src="https://user-images.githubusercontent.com/686243/178941047-c940262b-39c4-46c9-badf-d08134c63a4d.png">

**Comment by vedatyilmaz** [comment]
I'm on 4.12 Text Fields only shows default language, does not matter which tab are you. This happining  only index and details views.

Textarea works normal. I didnt try other field types

> Sure, but not on 4.12.x.



> Sure, but not on 4.12.x.



> Sure, but not on 4.12.x.



> Sure, but not on 4.12.x.

I'm on 4.12 Text Fields only shows default language, does not matter which tab are you. This happining  only index and details views.

Textarea works normal. I didnt try other field types.

**Comment by miks** [comment]
So, you have regular default language value instead of json with 4.12?

**Comment by vedatyilmaz** [comment]
> 

Yes. Only for Text field.

**Comment by Tarpsvo** [comment]
Heya! Seems like Nova 4.12 introduced a weird "displayedAs" behaviour which overrides the actual value of the field. It is now fixed in nova-translatable 2.0.5. Good luck!
