### ISSUE TITLE
Slug not updated on translatable fields

### ISSUE THREAD

**Issue by ramonfeleus** [outl1ne/nova-translatable#84]
When I use a translatable Slug field linked to another translatable field the slug is not entered in the field.
```php
           Text::make(__('Title'), 'title')
                ->rules('required')
                ->sortable()
                ->translatable(),
           Slug::make(__('Slug'), 'slug')->from('title.nl')->separator('-')
                ->rules('required')
                ->sortable()
                ->translatable(),
````
Instead in the chrome console I get 404 errors with javascript trying to request non-existant api url's for both languages (nl and en):
`/nova-api/undefined/field/slug.nl/preview`
`/nova-api/undefined/field/slug.en/preview`
Which throws the following error twice:
`
Uncaught (in promise) Error: Request failed with status code 404
    at e.exports (createError.js:16:15)
    at e.exports (settle.js:17:12)
    at XMLHttpRequest.y (xhr.js:54:7)
e.exports @ createError.js:16
e.exports @ settle.js:17
y @ xhr.js:54
await in y (async)
y @ debounce.js:95
A @ debounce.js:144
w @ debounce.js:132
setTimeout (async)
w @ debounce.js:135
setTimeout (async)
w @ debounce.js:135
setTimeout (async)
b @ debounce.js:103
_ @ debounce.js:172
emit @ index.js:36
$emit @ app.js:289
emitFieldValueChange @ FormEvents.js:21
handleChange @ FormField.js:76
onInput.t.<computed>.t.<computed> @ TextField.vue:11
nn @ runtime-core.esm-bundler.js:155
rn @ runtime-core.esm-bundler.js:164
n @ runtime-dom.esm-bundler.js:370
`.

When I change the slug field configuration to the following I get no 404 errors, but still an empty slug field:
```php
Slug::make(__('Slug'), 'slug')->from('title')
```

I'm using the following:
- Laravel framework 9.34.0
- Nova 4.15.2
- PHP 8.1
- Nova translatable 2.1.1

Is anybody else experiencing this, is there a solution available?

**Comment by Tarpsvo** [comment]
Oof. Nova has completely redone the way they handle the slug field. I don't see a solution to this right now. :(

**Comment by marcelosantos89** [comment]
I'm using use Outl1ne\PageManager\Nova\Fields\PrefixSlugField instead of Nova Slug and it works maybe it's a temporary solutions i think it works
