### ISSUE TITLE
add dusk identifiers to languages (LocaleTabs) 

### ISSUE THREAD

**Issue by chrillep** [outl1ne/nova-translatable#85]
![Skärmavbild 2022-10-11 kl  11 53 27](https://user-images.githubusercontent.com/1267931/195058759-bb91b9aa-31f9-4d30-98c5-a575b97c4df2.png)

```html
<a class="ml-3 cursor-pointer font-bold text-80 text-sm text-primary border-b-2 border-primary">
      English
</a>
```

easier to click via dusk if they had a dusk identifier like translatable or any identifier that is unique

ex. dusk="translatable.{attribute}.{locale}" for the nova field named title
 
 ```html   
    <a class="ml-3 cursor-pointer font-bold text-80 text-sm text-primary border-b-2 border-primary" 
     dusk="translatable.title.en"
    >
      English
</a>
```

**Comment by chrillep** [comment]
:dusk="errorAttributes[locale.key] + '.locale.tab'"

**Comment by chrillep** [comment]
https://github.com/kraenkvisuell/nova-astrotranslatable/pull/4/files

**Comment by Tarpsvo** [comment]
Heya! Added them in version 2.1.2. Good luck!

**Comment by chrillep** [comment]
yay thank you eases the e2e tests by a mile!
