### ISSUE TITLE
Markdown field not working on details view

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [outl1ne/nova-translatable#93]
<img width="1820" alt="image" src="https://user-images.githubusercontent.com/2553512/222148605-a0619d5f-2f6d-4e4d-ab5a-024cbfbdd2f1.png">
At the screenshot, the `Answer` field filled with data and has type `Markdown`, but displays like a null.

**Comment by Tarpsvo** [comment]
Heya! Thanks  a ton for the report and thanks to @lonnylot for fixing this issue. Released in 2.2.0.
