### ISSUE TITLE
Translatable Slug ->from() not working

### ISSUE THREAD

**Issue by mialyGit** [outl1ne/nova-translatable#98]
How make translatable Slug with nova 4 like this:
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\Slug;

            Text::make('Name', 'name')
                ->rules('required')
                ->translatable(),

            Slug::make('Slug')
            ->from('name')
            ->translatable()

**Comment by mialyGit** [comment]
@Tarpsvo this is not working 
Slug don't fill automatically

**Comment by Tarpsvo** [comment]
Ah crap, seems Nova's updates have broken it.

**Comment by mialyGit** [comment]
I use Nova 4.25.1
Please , Can You fix it , this is very useful

**Comment by marcelosantos89** [comment]
If you use Outl1ne\PageManager\Nova\Fields\PrefixSlugField field for the slug it translates it's from another package but it does work.

**Comment by mialyGit** [comment]
@marcelosantos89 thank you 
I have installed the package https://github.com/outl1ne/nova-page-manager and this works very well 
code (if any one need code) :

```
public function tools()
    {
        return [
          new \Outl1ne\PageManager\PageManager()
        ];
    }
```

```
public function fields(NovaRequest $request)
    {
        return [
            Text::make(__('Name'), 'name')
                        ->rules('required')
                        ->translatable(),
            PrefixSlugField::make('Slug')
                        ->from('name.*')
                        ->rules('required')
                        ->translatable()
           ];
    }
```

**Comment by ZakariaTlilani** [comment]
> If you use Outl1ne\PageManager\Nova\Fields\PrefixSlugField field for the slug it translates it's from another package but it does work.

No more work , Nova : 4.32.14
